### ISSUE TITLE
Function to obtain web3 instance injected by Mist / Metamask

### ISSUE THREAD

**Issue by martinklepsch** [district0x/cljs-web3#7]
Hey again :) I was looking through the core namespace and documentation and was just wondering if there's a built in way to obtain the web3 object injected by Metamask et al? 

If there's not then maybe it's worth to add this? Not sure how easy this is to uniformly implement across Mist / Metamask /... but currently users need to extern `js/window.web3` themselves which introduces some avoidable friction in using this library.

**Comment by madvas** [comment]
Hi, 
well, web3 object can be always accessed as `js/web3`, whether it's injected by Mist, MetaMask or any dapp browser. We may add wrapper function around that, but I think it's fairly short notation already.

**Comment by madvas** [comment]
yeah, true. I personally always use `aget` `aset` `js-invoke`, so I don't need to care about externs. Another trick is to have `cljsjs/web3` just in your `project.clj`, that will include externs in your compilation, even if you don't `:require` it in code.

**Comment by martinklepsch** [comment]
`aget` is for array access and that it works for object access is an implementation detail. So really users should be using `goog.object`, `cljs-oops` or some other JS interop tool. Given that there's a variety of ways to do this and given that almost everybody will have to do it I feel like providing this function as part of this library could be beneficial in helping people to get started.

**Comment by madvas** [comment]
Sure, I'm bit busy with other work these days, but if you could prepare PR I'll be happy to merge ;) Thank you

**Comment by martinklepsch** [comment]
Sure, I'd be happy to.
